config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users

  get "flights" => "flights#index"
  post "flights/search" => "flights#search"

  get "payments/:flight_id" => "payments#payment", as: :payment
  get "payments" => "payments#payment_success", as: :payment_success

  get "bookings/create" => "bookings#create_booking", as: :create_booking
  get "bookings/search" => "bookings#search", as: :search_booking
  get "bookings/search_result" => "bookings#search_result", as: :search_result
  get "bookings" => "bookings#index", as: :bookings
  post "bookings" => "bookings#new_booking_details"
  get "bookings/new" => "bookings#new_booking_page", as: :new_booking
  get "bookings/:id/edit" => "bookings#edit", as: :edit_booking
  get "bookings/:id" => "bookings#show", as: :booking
  patch "bookings/:id" => "bookings#update"
  put "bookings/:id" => "bookings#update"
  delete "bookings/:id" => "bookings#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :arriving_flights,
           foreign_key: :arrival_airport_id,
           class_name: "Flight"
  has_many :departing_flights,
           foreign_key: :departure_airport_id,
           class_name: "Flight"

  validates :name, presence: true
  validates :state, presence: true
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  belongs_to :user
  has_many :passengers

  validates :booking_ref_code, presence: true
  validates :flight_id, presence: true
  validates :total_price, presence: true

  accepts_nested_attributes_for :passengers,
                                allow_destroy: true
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :departure_airport, class_name: "Airport"
  has_many :bookings

  validates :airline_name, presence: true
  validates :arrival_airport_id, presence: true
  validates :arrival_date, presence: true
  validates :available_seats, presence: true
  validates :departure_airport_id, presence: true
  validates :departure_date, presence: true
  validates :flight_code, presence: true
  validates :price, presence: true

  def self.available_flights
    current_time = DateTime.tomorrow
    where("departure_date >= ?", current_time).sort_by_departure_date
  end

  def self.search(search_params)
    sql_query = "departure_date >= ? and available_seats > ?"
    flights = where(
      sql_query,
      search_params[:departure_date].to_datetime,
      search_params[:number_of_passengers].to_i
    )
    flights.sort_by_departure_date.select do |flight|
      flight.departure_airport_id == search_params[:from].to_i &&
        flight.arrival_airport_id == search_params[:to].to_i
    end
  end

  def self.sort_by_departure_date
    order("departure_date")
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking

  validates :email, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings

  validates :email, presence: true
  validates :password, presence: true
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [
    :index,
    :edit,
    :update,
    :destroy,
    :search,
    :search_result
  ]

  def new_booking_page
    if params[:flight_id]
      session.delete(:info)
      @selected_flight = Flight.find(params[:flight_id])
      @booking = Booking.new
      number_of_passengers = params[:number_of_passengers].to_i
      number_of_passengers.times { @booking.passengers.build }
    else
      redirect_to flights_path, alert: "Please select a flight first"
    end
  end

  def new_booking_details
    if params[:booking][:passengers_attributes].any?
      flight_id = params[:booking][:flight_id]
      session[:info] = { payment_type: "new_booking" }
      session[:info][:booking] = booking_params
      redirect_to payment_path(flight_id)
    else
      redirect_to flights_path, alert: "Please enter the passenger(s) info"
    end
  end

  def create_booking
    if session[:info]
      @booking = Booking.new(session[:info]["booking"])
      @booking.booking_ref_code = session[:info]["token"]
      @booking.user_id = current_user.id if current_user
      @booking.save
      redirect_to(booking_path(@booking), notice: "Payment successful")
      UltraMailer.mail_user(@booking, current_user)
      session.delete(:info)
    else
      redirect_to flights_path, alert: "Error creating your booking"
    end
  end

  def show
    if @booking
      @selected_flight = @booking.flight
      @passengers = Passenger.where(booking_id: @booking.id)
    else
      redirect_to flights_path, alert: "Booking record not found"
    end
  end

  def index
    @bookings = current_user.bookings
  end

  def edit
    @selected_flight = @booking.flight
  end

  def update
    session.delete(:info)
    params[:booking][:flight_id] = @booking.flight_id
    session[:info] = { booking: booking_params }
    session[:info][:id] = params[:id]
    if @booking.update(booking_params)
      redirect_to payment_path(@booking.flight_id)
    else
      redirect_to edit_booking_path(@booking), notice: "Enter all Fields"
    end
  end

  def destroy
    redirect_to bookings_path, notice: "Booking cancelled" if @booking.destroy
  end

  def search
  end

  def search_result
    @booking = Booking.find_by(booking_ref_code: params[:booking_ref_code])
    if @booking
      redirect_to booking_path(@booking.id)
    else
      redirect_to search_booking_path, notice: "Booking not found"
    end
  end

  def booking_params
    params.require(:booking).permit(
      :flight_id,
      :user_id,
      :booking_ref_code,
      :total_price,
      :number_of_passengers,
      passengers_attributes: [:id, :name, :email, :_destroy]
    )
  end

  def set_booking
    @booking = Booking.find_by_id(params[:id]) if params[:id]
  end

  private :booking_params, :set_booking
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.available_flights
  end

  def search
    @flights = Flight.search(search_params)
  end

  def search_params
    params.permit(:from, :to, :departure_date, :number_of_passengers)
  end

  private :search_params
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @airports = Airport.select(:id, :name)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def payment
    if params[:flight_id] && session[:info]
      payment_service = instantiate_payment_service
      response = payment_service.make_payment
      session[:info]["token"] = response.token
      redirect_to(response.redirect_uri)
    else
      redirect_to root_path, alert: "Your Booking information is required"
    end
  end

  def instantiate_payment_service
    selected_flight = Flight.find(params[:flight_id])
    PaymentService.new(
      selected_flight: selected_flight,
      validate_url: payment_success_url,
      contact_url: root_url,
      total_cost: session[:info]["booking"]["total_price"].to_i
    )
  end

  def payment_success
    if (session[:info]["token"] == params[:token]) &&
       (session[:info]["payment_type"] == "new_booking")
      redirect_to create_booking_path
    else
      @booking = Booking.find(session[:info]["id"])
      UltraMailer.mail_user(@booking, current_user)
      session.delete(:info)
      redirect_to booking_path(@booking), notice: "Your update was successful."
    end
  end

  private :instantiate_payment_service
end

app/views/bookings/_booking_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Passengers Details</h3>
  </div>
  <% flash[:notice] %>
  <div class="panel-body">
    <%= form_for(@booking) do |f| %>

      <%= f.hidden_field :flight_id, { value: params['flight_id'] } %>
      <%= f.hidden_field :total_price, { value: "#{@selected_flight.price}", class: "cost_tracker" } %>

      <%= f.fields_for :passengers do |passenger| %>
        <%= render 'passenger_fields', :f => passenger %>
      <% end %>

      <div class="links panel-footer">
        <%= link_to_add_association 'Add Passenger', f, :passengers, class: 'btn btn-primary', onclick: 'adder()' %>
        <%= f.submit 'Book Flight', class: "btn btn-primary pull-right smtbook" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/_passenger_fields.html.erb
<div class="nested-fields form-inline" id ="nested-fields">
  <div class="form-group">
    <%= f.text_field :name, { id: 'passenger_name', class: "validate form-control", type: "text", placeholder: 'Passenger Name', required: true, pattern: "^[a-zA-Z]+[\-'\s]?[a-zA-Z ]+$" } %>
  </div>
  <span>~</span>
  <div class="form-group">
    <%= f.text_field :email, { id: 'passenger_email', class: "validate form-control", type: "email", placeholder: 'Passenger Email', required: true, pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" } %>
  </div>
  <div class="links pull-right">
    <%= link_to_remove_association 'Delete', f, class: 'btn btn-danger rm_pass', onclick: 'remover()' %>
  </div>
  <hr>
</div>

app/views/bookings/edit.html.erb
<div class="pages">
  <div class ="container">
    <%= bootstrap_flash %>
    <div class ="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class ="panel-body ">
            <h4 class="">Booking Reference: <strong><%= @booking.booking_ref_code%></strong></h4>
            <br>
            <p align="center">Booking for <%= @selected_flight.airline_name %> - <%= @selected_flight.flight_code %>
            <br>
            <p>Flight Code: <strong><%= @selected_flight.flight_code %></strong></p>
            <p>Airline: <strong><%= @selected_flight.airline_name %></strong></p>
            <p>Departure: <strong><%= @selected_flight.departure_airport.name %></strong></p>
            <p>Destination: <strong><%= @selected_flight.arrival_airport.name %></strong></p>
            <p>Take Off Date: <strong><%= @selected_flight.departure_date.try(:strftime, "%d - %m - %Y") %></strong></p>
            <p>Take Off Time: <strong><%= @selected_flight.departure_date.try(:strftime, '%l:%M%P') %></strong></p>
            <p>Cost/Passenger: <strong class="cost"><%= number_to_currency(@selected_flight.price, locale: :us) %></strong></p>
            <p>Passenger(s): <strong class="pass_num"><%= params[:number_of_passengers].to_i %></strong></p>
            <p>Total Cost: <strong class="total"><%= number_to_currency((@selected_flight.price * params[:number_of_passengers].to_i ), locale: :us)%></strong></p>
            <br>
            <% if @selected_flight.departure_date >= DateTime.now %>
              <%= link_to 'Cancel Booking', @booking, method: :delete, data: { confirm: 'Are you sure?'},class: "btn btn-danger"  %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <% if @selected_flight.departure_date >= DateTime.now %>
          <%= render 'booking_form' %>
        <% else %>
          <p class= "alert-warning"> Your flight has taken off <p>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class= "pages">
  <div class="container">
  <%= bootstrap_flash %>
    <div class="row" align ="center">
      <div class="col-md-12">

        <% if @bookings.count > 0 %>
          <table class="table">
            <h4>Bookings Summary</h4>

            <thead>
              <tr>
                <th>Ref. no</th>
                <th>Airline</th>
                <th>Departure Airport</th>
                <th>Arrival Airport</th>
                <th>Departure Date</th>
              </tr>
            </thead>

            <tbody>
              <% @bookings.each do |booking| %>
                <% if booking.user_id == current_user.id %>
                  <tr>
                  <td><%= booking.booking_ref_code %></td>
                  <td><%= booking.flight.airline_name %></td>
                  <td><%= booking.flight.departure_airport.name %></td>
                  <td><%= booking.flight.arrival_airport.name %></td>
                  <td><%= booking.flight.departure_date.strftime("%d - %m - %Y") %></td>
                  <td><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-search", title: "View"), booking %></td>
                  <td><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-edit", title: "Edit"), edit_booking_path(booking) %></td>
                  <td><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-trash", title: "Delete"), booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% else %>
                  <a href="/flights" class ="btn btn-primary">Book A flight now</a>
                <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>

        <% else %>
          <a href="/flights" class ="btn btn-primary">Book A flight now</a>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/new_booking_page.html.erb
<div class="pages">
  <div class="container">
    <div class="row">

      <div class="col-md-5">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Flight Information</h3>
          </div>
          <div class="panel-body">
            <p>Flight Code: <strong><%= @selected_flight.flight_code %></strong></p>
            <p>Airline: <strong><%= @selected_flight.airline_name %></strong></p>
            <p>Departure: <strong><%= @selected_flight.departure_airport.name %></strong></p>
            <p>Destination: <strong><%= @selected_flight.arrival_airport.name %></strong></p>
            <p>Take Off Date: <strong><%= @selected_flight.departure_date.try(:strftime, "%d - %m - %Y") %></strong></p>
            <p>Take Off Time: <strong><%= @selected_flight.departure_date.try(:strftime, '%l:%M%P') %></strong></p>
            <p>Cost/Passenger: <strong class="cost"><%= number_to_currency(@selected_flight.price, locale: :us) %></strong></p>
            <p>Passenger(s): <strong class="pass_num"><%= params[:number_of_passengers].to_i %></strong></p>
            <p>Total Cost: <strong class="total"><%= number_to_currency((@selected_flight.price * params[:number_of_passengers].to_i ), locale: :us)%></strong></p>
          </div>
        </div>
      </div>

      <div class="col-md-7">
        <%= render 'booking_form' %>
      </div>

    </div>
  </div>
</div>

app/views/bookings/search.html.erb
<div class="pages row">
  <div class="container">
    <%= bootstrap_flash %>
  </div>
  <div class="col-sm-offset-5">
    <%= form_tag(search_result_path, method: "get", enforce_utf8: false) do %>
      <div class="">
        <%= text_field_tag :booking_ref_code, nil, placeholder: "Enter your booking reference number", required: true, size: 35 %>
      </div>
      <br>
      <div class="col-sm-offset-1">
        <%= submit_tag "Search Bookings", name: nil, class: "btn btn-primary center" %>
      </div>
      <div class="container" id="search-result-container">
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="pages">
  <div class="container center">
    <%= bootstrap_flash %>
    <div class="row">
      <div class="col-md-12">
        <h2 align="center" class="text-info"><small>Your Booking For Flight</small> "<%= @selected_flight.airline_name %> #<%= @selected_flight.flight_code %>" <small>from</small> <%= @selected_flight.departure_airport.state %> <small>to</small> <%= @selected_flight.arrival_airport.state %> <small>was successful.</small></h2>
        <hr>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <h3 class="text-info" ><strong>Flight Details</strong></h3>
        <hr>
        <h4><strong>Airline:</strong> <%= @selected_flight.airline_name %></h4>
        <h4><strong>From:</strong> <%= @selected_flight.departure_airport.name %></h4>
        <h4><strong>To:</strong> <%= @selected_flight.arrival_airport.name %></h4>
        <h4><strong><h4><strong>Take off date:</strong>
        <%= @selected_flight.departure_date.strftime('%d - %m - %Y') %>, <%= @selected_flight.departure_date.strftime('%-l:%M%P') %></h4>
        <h4><strong>Landing Date: </strong></strong>
        <%= @selected_flight.arrival_date.strftime('%d - %m - %Y') %>, <%= @selected_flight.arrival_date.strftime('%-l:%M%P') %></h4>
        <h4><strong>No of seats reserved:</strong> <%= @passengers.count %></h4>
        <h4><strong>Total Price: </strong><%= number_to_currency(@booking.total_price, locale: :us) %>  </h4>
      </div>

      <div class="col-md-4">
        <h3 class="text-info"> <strong>Passengers Details</strong></h3>
        <hr>
        <% @passengers.each do |passenger| %>
        <p>Name: <%= passenger.name %> </p>
        <p>Email: <%= passenger.email %></p>
        <hr>
        <% end %>
      </div>

      <% if current_user %>
        <% if current_user.id == @booking.user_id %>
          <div class = "col-md-2">
            <span class="pull-right">
            <%= link_to content_tag(:i, '', class: "glyphicon glyphicon-edit btn btn-primary", title: "Edit"), edit_booking_path(@booking) %>
            <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash btn btn-primary", title: "Delete"), @booking, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/flights/_flights.html.erb
<%= form_tag({controller: 'bookings', action: 'new_booking_page'}, method: 'get') do %>
<input name="number_of_passengers" type="hidden" value= <%= params[:number_of_passengers] %> />
  <% @flights.each do |flight| %>
    <li class="list-group-item flight-list">
      <div class="container center">
        <div class="row">

          <div class="col-md-2 text-center vertical-align search-airline">
            <div class="radio-danger">
              <%= radio_button_tag(:flight_id, flight.id, checked=false, required: true) %>
            </div>
            <%= label_tag "flights_id_#{flight.id}", flight.airline_name %>
          </div>

          <div class="col-md-3">
            <i class="fa fa-plane"></i>
            <h5><%= flight.departure_date.try(:strftime, '%-l:%M%P') %></h5>
            <p><%= flight.departure_date.try(:strftime, "%d - %m - %Y") %></p>
            <%= flight.departure_airport.name %>
          </div>

          <div class="col-md-3">
            <i class="fa fa-plane fa-flip-vertical"></i>
            <h5><%= flight.arrival_date.try(:strftime, '%-l:%M%P') %></h5>
            <p><%= flight.arrival_date.try(:strftime, "%d - %m - %Y") %></p>
            <%= flight.arrival_airport.name %>
          </div>

          <div class="col-md-3 search-price">
            <span><%= number_to_currency(flight.price, locale: :us) %></span><span>/person</span>
            <br>
            <span><%= submit_tag 'Select Flight', class: "btn btn-primary" %></span>
          </div>

        </div>
      </div>
    </li>
    <hr>
  <% end %>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_tag({controller: 'flights', action: 'search'}, method: 'post', remote: true, class: 'search-flight') do %>
  <div class="form-group">
    <%= label_tag :from, "Departure Airport?" %>
    <%= select_tag :from, options_for_select(@airports.collect { |airport| [airport.name, airport.id] }), { class: "form-control  transparent-input", required: true } %>
  </div>

  <div class="form-group">
    <%= label_tag :to, "Arrival Airport?" %>
    <%= select_tag :to, options_for_select(@airports.collect { |airport| [airport.name, airport.id] }), { class: "form-control  transparent-input", required: true } %>
  </div>

  <div class="form-group">
    <%= label_tag :number_of_passengers, "How many Passengers?" %>
    <%= select_tag :number_of_passengers, options_for_select((1..10)), { class: "form-control  transparent-input", required: true } %>
  </div>

  <div class="form-group">
    <%= label_tag :departure_date, "When do you want to leave?" %>
    <div class="input-group">
      <%= text_field_tag :departure_date, nil, { class: "datepicker form-control transparent-input", required: true } %>
      <label for="date-picker" class="input-group-addon btn">
        <span class="glyphicon glyphicon-calendar"></span>
      </label>
    </div>
  </div>

  <%= submit_tag 'Search Flights', class: 'btn btn-default btn-lg btn-block', onclick: "validateFields(event)" %>
<% end %>

app/views/flights/_search_result.html.erb
<div class="home-result">
  <div class="panel-body" align ="center">
    <% if @flights.empty? %>
      <h4 class="text-info">No Flights found for the specified locations</h4>
    <% else %>
      <h2 class="text-info"><small>Search results for flights from</small>
        <%= @flights.first.departure_airport.state %> <small>to</small> <%= @flights.first.arrival_airport.state %>
        <small>starting from</small> <%= DateTime.parse(params[:departure_date]).strftime("%b %d, %Y") %>
      </h2>
      <hr>
      <%= render 'flights/flights' %>
    <% end %>
    <br>
    <%= link_to 'All Flights', flights_path, class: "btn btn-primary pull-right"%>
    <%= link_to 'close', :back, class: "btn btn-danger pull-left"%>
  </div>
</div>

app/views/flights/index.html.erb
<div class="pages">
  <div class= "container">
    <div class= "row  myFlights">
    <%= bootstrap_flash %>
      <div class = "col-md-12">
        <div class="panel-body" align ="center">
          <h3>All Flights</h3>
        <%= render 'flights/flights' %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/flights/search.js.erb
$(document).ready(function(){
$('div#all-flights').empty().html("<%= j render 'flights/search_result' %>");
$('html, body').animate({
  scrollTop: $("#result-view").offset().top
  }, 2000);
});

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">

  <div class="container container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "UltraFly", root_path, class: "navbar-brand logo-text" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "All Flights", flights_path %></li>
        <% unless current_user %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% else %>
        <li><%= link_to "Manage Bookings", search_booking_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Past Bookings", bookings_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ultrafly</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<section id="main-view" data-speed="6" data-type="background">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 well pull-right">
        <%= bootstrap_flash %>
        <h1>UltraFly</h1>
        <p>Online flight reservation just got better!</p>
        <br>
        <%= render 'flights/search_form' %>
      </div>
    </div>
  </div>
</section>

<section id="result-view" data-speed="6" data-type="background">
  <div class="container" id="all-flights">
  </div>
</section>